python ./codecoach.py  ./test/1.py > output.txt
python ./codecoach.py  ./test/2.py >> output.txt
python ./codecoach.py  ./test/3.py > output.txt
python ./codecoach.py  ./test/4.py >> output.txt
python ./codecoach.py  ./test/5.py >> output.txt
python ./codecoach.py  ./test/6.py >> output.txt
python ./codecoach.py  ./test/7.py >> output.txt
python ./codecoach.py  ./test/8.py >> output.txt
python ./codecoach.py  ./test/9.py >> output.txt
python ./codecoach.py  ./test/10.py >> output.txt
python ./codecoach.py  ./test/11.py >> output.txt
python ./codecoach.py  ./test/12.py >> output.txt
python ./codecoach.py  ./test/13.py >> output.txt
python ./codecoach.py  ./test/14.py >> output.txt
python ./codecoach.py  ./test/15.py >> output.txt
python ./codecoach.py  ./test/16.py >> output.txt
python ./codecoach.py  ./test/17.py >> output.txt
python ./codecoach.py  ./test/18.py >> output.txt
python ./codecoach.py  ./test/19.py >> output.txt
python ./codecoach.py  ./test/20.py >> output.txt
python ./codecoach.py  ./test/21.py >> output.txt
python ./codecoach.py  ./test/22.py >> output.txt
python ./codecoach.py  ./test/24.py >> output.txt
python ./codecoach.py  ./test/25.py >> output.txt
python ./codecoach.py  ./test/29.py >> output.txt
python ./codecoach.py  ./test/30.py >> output.txt
python ./codecoach.py  ./test/31.py >> output.txt
python ./codecoach.py  ./test/32.py >> output.txt
python ./codecoach.py  ./test/33.py >> output.txt
python ./codecoach.py  ./test/34.py >> output.txt
python ./codecoach.py  ./test/35.py >> output.txt
python ./codecoach.py  ./test/36.py >> output.txt
python ./codecoach.py  ./test/37.py >> output.txt
python ./codecoach.py  ./test/38.py >> output.txt
python ./codecoach.py  ./test/39.py >> output.txt
python ./codecoach.py  ./test/40.py >> output.txt
python ./codecoach.py  ./test/41.py >> output.txt
python ./codecoach.py  ./test/42.py >> output.txt
python ./codecoach.py  ./test/43.py >> output.txt
python ./codecoach.py  ./test/44.py >> output.txt
python ./codecoach.py  ./test/45.py >> output.txt
python ./codecoach.py  ./test/46.py >> output.txt
python ./codecoach.py  ./test/47.py >> output.txt
python ./codecoach.py  ./test/48.py >> output.txt
python ./codecoach.py  ./test/49.py >> output.txt
python ./codecoach.py  ./test/50.py >> output.txt
python ./codecoach.py  ./test/51.py >> output.txt
python ./codecoach.py  ./test/52.py >> output.txt
python ./codecoach.py  ./test/53.py >> output.txt
python ./codecoach.py  ./test/54.py >> output.txt
python ./codecoach.py  ./test/55.py >> output.txt
python ./codecoach.py  ./test/56.py >> output.txt
python ./codecoach.py  ./test/57.py >> output.txt
python ./codecoach.py  ./test/59.py >> output.txt
python ./codecoach.py  ./test/61.py >> output.txt
python ./codecoach.py  ./test/62.py >> output.txt
python ./codecoach.py  ./test/63.py >> output.txt
python ./codecoach.py  ./test/64.py >> output.txt
python ./codecoach.py  ./test/65.py >> output.txt
python ./codecoach.py  ./test/67.py >> output.txt
python ./codecoach.py  ./test/68.py >> output.txt
python ./codecoach.py  ./test/69.py >> output.txt
python ./codecoach.py  ./test/70.py >> output.txt
python ./codecoach.py  ./test/71.py >> output.txt
python ./codecoach.py  ./test/72.py >> output.txt
python ./codecoach.py  ./test/73.py >> output.txt
python ./codecoach.py  ./test/74.py >> output.txt
python ./codecoach.py  ./test/75.py >> output.txt
python ./codecoach.py  ./test/76.py >> output.txt
python ./codecoach.py  ./test/77.py >> output.txt
python ./codecoach.py  ./test/78.py >> output.txt
python ./codecoach.py  ./test/79.py >> output.txt
python ./codecoach.py  ./test/80.py >> output.txt
python ./codecoach.py  ./test/81.py >> output.txt
python ./codecoach.py  ./test/82.py >> output.txt
python ./codecoach.py  ./test/83.py >> output.txt
python ./codecoach.py  ./test/84.py >> output.txt
python ./codecoach.py  ./test/85.py >> output.txt
python ./codecoach.py  ./test/86.py >> output.txt
python ./codecoach.py  ./test/87.py >> output.txt
python ./codecoach.py  ./test/88.py >> output.txt
python ./codecoach.py  ./test/89.py >> output.txt
python ./codecoach.py  ./test/90.py >> output.txt
python ./codecoach.py  ./test/91.py >> output.txt
python ./codecoach.py  ./test/92.py >> output.txt
python ./codecoach.py  ./test/93.py >> output.txt
python ./codecoach.py  ./test/94.py >> output.txt
python ./codecoach.py  ./test/95.py >> output.txt
python ./codecoach.py  ./test/96.py >> output.txt
python ./codecoach.py  ./test/97.py >> output.txt
python ./codecoach.py  ./test/98.py >> output.txt
python ./codecoach.py  ./test/99.py >> output.txt
python ./codecoach.py  ./test/100.py >> output.txt
python ./codecoach.py  ./test/101.py >> output.txt
python ./codecoach.py  ./test/102.py >> output.txt
python ./codecoach.py  ./test/103.py >> output.txt
python ./codecoach.py  ./test/104.py >> output.txt
python ./codecoach.py  ./test/105.py >> output.txt
python ./codecoach.py  ./test/106.py >> output.txt
python ./codecoach.py  ./test/107.py >> output.txt
python ./codecoach.py  ./test/108.py >> output.txt
python ./codecoach.py  ./test/109.py >> output.txt
python ./codecoach.py  ./test/110.py >> output.txt
python ./codecoach.py  ./test/111.py >> output.txt
python ./codecoach.py  ./test/112.py >> output.txt
python ./codecoach.py  ./test/113.py >> output.txt
python ./codecoach.py  ./test/114.py >> output.txt
python ./codecoach.py  ./test/115.py >> output.txt
python ./codecoach.py  ./test/116.py >> output.txt
python ./codecoach.py  ./test/117.py >> output.txt
python ./codecoach.py  ./test/118.py >> output.txt
python ./codecoach.py  ./test/119.py >> output.txt
python ./codecoach.py  ./test/120.py >> output.txt
python ./codecoach.py  ./test/121.py >> output.txt
python ./codecoach.py  ./test/122.py >> output.txt
python ./codecoach.py  ./test/123.py >> output.txt
python ./codecoach.py  ./test/124.py >> output.txt
python ./codecoach.py  ./test/125.py >> output.txt
python ./codecoach.py  ./test/126.py >> output.txt
python ./codecoach.py  ./test/127.py >> output.txt
python ./codecoach.py  ./test/128.py >> output.txt
python ./codecoach.py  ./test/129.py >> output.txt
python ./codecoach.py  ./test/130.py >> output.txt
python ./codecoach.py  ./test/131.py >> output.txt
python ./codecoach.py  ./test/132.py >> output.txt
python ./codecoach.py  ./test/133.py >> output.txt
python ./codecoach.py  ./test/134.py >> output.txt
python ./codecoach.py  ./test/135.py >> output.txt
python ./codecoach.py  ./test/136.py >> output.txt
python ./codecoach.py  ./test/137.py >> output.txt
python ./codecoach.py  ./test/138.py >> output.txt
python ./codecoach.py  ./test/139.py >> output.txt
python ./codecoach.py  ./test/140.py >> output.txt
python ./codecoach.py  ./test/141.py >> output.txt
python ./codecoach.py  ./test/142.py >> output.txt
python ./codecoach.py  ./test/143.py >> output.txt
python ./codecoach.py  ./test/144.py >> output.txt
python ./codecoach.py  ./test/145.py >> output.txt
python ./codecoach.py  ./test/146.py >> output.txt
python ./codecoach.py  ./test/147.py >> output.txt
python ./codecoach.py  ./test/148.py >> output.txt
python ./codecoach.py  ./test/149.py >> output.txt
python ./codecoach.py  ./test/150.py >> output.txt
python ./codecoach.py  ./test/151.py >> output.txt
python ./codecoach.py  ./test/152.py >> output.txt
python ./codecoach.py  ./test/153.py >> output.txt
python ./codecoach.py  ./test/154.py >> output.txt
python ./codecoach.py  ./test/155.py >> output.txt
python ./codecoach.py  ./test/156.py >> output.txt
python ./codecoach.py  ./test/157.py >> output.txt
python ./codecoach.py  ./test/158.py >> output.txt
python ./codecoach.py  ./test/159.py >> output.txt
python ./codecoach.py  ./test/160.py >> output.txt
python ./codecoach.py  ./test/161.py >> output.txt
python ./codecoach.py  ./test/162.py >> output.txt
python ./codecoach.py  ./test/163.py >> output.txt
python ./codecoach.py  ./test/164.py >> output.txt
python ./codecoach.py  ./test/165.py >> output.txt
python ./codecoach.py  ./test/166.py >> output.txt
python ./codecoach.py  ./test/167.py >> output.txt
python ./codecoach.py  ./test/168.py >> output.txt
python ./codecoach.py  ./test/169.py >> output.txt
python ./codecoach.py  ./test/170.py >> output.txt
python ./codecoach.py  ./test/171.py >> output.txt
python ./codecoach.py  ./test/172.py >> output.txt
python ./codecoach.py  ./test/173.py >> output.txt
python ./codecoach.py  ./test/174.py >> output.txt
python ./codecoach.py  ./test/175.py >> output.txt
python ./codecoach.py  ./test/176.py >> output.txt
python ./codecoach.py  ./test/177.py >> output.txt
python ./codecoach.py  ./test/178.py >> output.txt
python ./codecoach.py  ./test/179.py >> output.txt
python ./codecoach.py  ./test/180.py >> output.txt
python ./codecoach.py  ./test/181.py >> output.txt
python ./codecoach.py  ./test/182.py >> output.txt
python ./codecoach.py  ./test/183.py >> output.txt
python ./codecoach.py  ./test/184.py >> output.txt
python ./codecoach.py  ./test/185.py >> output.txt
python ./codecoach.py  ./test/186.py >> output.txt
python ./codecoach.py  ./test/187.py >> output.txt
python ./codecoach.py  ./test/188.py >> output.txt
python ./codecoach.py  ./test/189.py >> output.txt
python ./codecoach.py  ./test/190.py >> output.txt
python ./codecoach.py  ./test/191.py >> output.txt
python ./codecoach.py  ./test/192.py >> output.txt
python ./codecoach.py  ./test/193.py >> output.txt
python ./codecoach.py  ./test/194.py >> output.txt
python ./codecoach.py  ./test/195.py >> output.txt
python ./codecoach.py  ./test/196.py >> output.txt
python ./codecoach.py  ./test/197.py >> output.txt
python ./codecoach.py  ./test/198.py >> output.txt
python ./codecoach.py  ./test/199.py >> output.txt
python ./codecoach.py  ./test/200.py >> output.txt
python ./codecoach.py  ./test/201.py >> output.txt
python ./codecoach.py  ./test/202.py >> output.txt
python ./codecoach.py  ./test/203.py >> output.txt
python ./codecoach.py  ./test/204.py >> output.txt
python ./codecoach.py  ./test/205.py >> output.txt
python ./codecoach.py  ./test/206.py >> output.txt
python ./codecoach.py  ./test/207.py >> output.txt
python ./codecoach.py  ./test/208.py >> output.txt
python ./codecoach.py  ./test/209.py >> output.txt
python ./codecoach.py  ./test/210.py >> output.txt
python ./codecoach.py  ./test/211.py >> output.txt
python ./codecoach.py  ./test/212.py >> output.txt
python ./codecoach.py  ./test/213.py >> output.txt